Repository inoagents/react-project-kitchen-frontend, pull requests merged in 2021-06, with the labels that each got.

#2 add github action (test codestyle)
  .github/workflows/test.yml
Labels: feature

#14 feat: change component Login
  public/library.css
  src/components/App.js
  src/components/Header.js
  src/components/Login.js
  src/components/Login.module.css
  src/images/eyeIconClosed.svg
  src/images/eyeIconOpened.svg
  src/index.css
  src/store.js
Labels: feature

#26 Feat: add global styles
  .stylelintrc
  src/fonts/stylesheet.css
  src/index.css
  src/index.js
  src/index.module.css
Labels: feature

#27 Feat: rewrite Home component
  .stylelintrc
  src/components/App.js
  src/components/Home/Banner.js
  src/components/Home/Home.module.css
  src/components/Home/MainView.js
  src/components/Home/Tags.js
  src/components/Home/index.js
  src/reducers/common.js
Labels: feature

#28 Fix: additional changes in Home component
  .stylelintrc
  src/components/Home/Home.module.css
  src/index.module.css
Labels: bug

#29 fix: add hover effect to nav-links
  public/library.css
  src/components/Header.js
  src/components/Header.module.css
Labels: bug

#30 Feat: change profile
  src/components/App.js
  src/components/Home/Home.module.css
  src/components/Home/Tags.js
  src/components/Home/index.js
  src/components/Profile.js
  src/components/Profile.module.css
  src/components/ProfileFavorites.js
  src/components/Tags.js
  src/components/Tags.module.css
  src/constants/actionTypes.js
  src/index.module.css
  src/reducers/articleList.js
  src/reducers/common.js
  src/reducers/profile.js
Labels: feature

#31 Feature/article preview
  src/components/ArticleList.js
  src/components/ArticleList/ArticleList.js
  src/components/ArticleList/ArticleList.module.css
  src/components/ArticlePreview.js
  src/components/ArticlePreview/ArticlePreview.js
  src/components/ArticlePreview/ArticlePreview.module.css
  src/components/Home/MainView.js
  src/components/ListPagination.js
  src/components/ListPagination/ListPagination.js
  src/components/ListPagination/ListPagination.module.css
  src/components/Profile.js
  src/components/TagList.js
  src/components/Tags.module.css
  src/images/like.svg
  src/images/nextPage.svg
  src/images/prevPage.svg
  src/images/unlike.svg
Labels: feature

#34 feat: edit Settings component
  src/components/Header.js
  src/components/Register.js
  src/components/Settings.js
  src/components/Settings.module.css
  src/images/avatar.svg
Labels: feature

#35 Rewrited Editor component
  src/components/Editor.js
  src/components/Editor.module.css
  src/components/Tags.module.css
  src/images/paperClip.svg
  src/index.module.css
  src/reducers/editor.js
Labels: feature

#37 Project localization
  README.md
  src/components/ArticleList/ArticleList.js
  src/components/ArticlePreview/ArticlePreview.js
  src/components/Header.js
  src/images/alien.svg
  src/reducers/common.js
Labels: documentation

#43 fix: ArticlePreview layout bug
  src/components/ArticlePreview/ArticlePreview.module.css
Labels: bug

#40 feat: add in editor field image
  src/agent.js
  src/components/ArticlePreview/ArticlePreview.js
  src/components/Editor.js
  src/components/Editor.module.css
  src/components/Settings.js
  src/reducers/editor.js
Labels: feature
